### PR TITLE
Issue #91: Add unset role operations in TokenManagementTransactionsFactory

### PR DESCRIPTION
**Pull request by cristure**
Handles https://github.com/multiversx/mx-sdk-py/issues/91.

### CODE REVIEW

**Comment by cristure** [comment]
I think it might be worth to address the fact that, for instance one cannot unset the `ESDTNFTCreate` special role. Therefore that makes the argument pretty pointless. But for posterity might be helpful to keep the same signature. @popenta, @andreibancioiu what do you guys think?

**Review by andreibancioiu — DISMISSED** [review]
Can we change the target branch, towards main?

**Comment by andreibancioiu** [comment]
> I think it might be worth to address the fact that, for instance one cannot unset the `ESDTNFTCreate` special role. Therefore that makes the argument pretty pointless. But for posterity might be helpful to keep the same signature. @popenta, @andreibancioiu what do you guys think?

Very good question!

Indeed, let's keep it (better symmetry). And yes, maybe at some point the protocol might allow this flow?

**Comment by popenta** [comment]
> Can we change the target branch, towards main?

I'm not sure we should set the target branch as `main`. It seems that the branch was created from `feat/next` and that contains some breaking stuff.

**Pull request closed without merging**
